### ISSUE TITLE
add new mixin ( fonts() )

### ISSUE THREAD

**Issue by reckek** [reckek/Starter#1]
add mixin in fule _mixins.scss

```scss
// <== FONTS ==>
@mixin font($font_name, $file_name, $weight, $style) {
  @font-face {
    src: url("../assets/fonts/#{$file_name}.woff") format("woff"), url("../assets/fonts/#{$file_name}.woff2") format("woff2");
    font-family: $font_name;
    font-weight: #{$weight}; // 100, 200, 300, 400, 500, 600, 700, 800, 900
    font-style: #{$style}; // normal, italic, oblique
    font-display: swap;
  }
}
```
